---
- hosts: all
  sudo: yes

  tasks:

    - name: Run 'apt-get update'
      apt: update_cache=yes

    - name: Install needed packages
      apt: pkg={{ item }} state=latest
      with_items:
        - python-pycurl
        - git

    - name: Add node.js ppa repository
      apt_repository: repo='ppa:chris-lea/node.js'

    - name: Install needed packages
      apt: pkg={{ item }} state=latest
      with_items:
        - nodejs

    - name: Install node.js
      apt: pkg={{ item }} state=latest
      with_items:
        - nodejs

    - name: npm install
      npm: path=/vagrant

    - name: bower install
      shell: 'cd /vagrant/; node_modules/.bin/bower --allow-root install'

    - name: Copy upstart script
      shell: 'cp /vagrant/dev/declutter_upstart /etc/init/declutter.conf'

    - name: Start server
      shell: sudo start declutter
