---
- hosts: all
  sudo: yes

  tasks:

    - name: Run 'apt-get update'
      apt: update_cache=yes

    - name: Install needed packages
      apt: pkg={{ item }} state=latest
      with_items:
        - python-pycurl
        - git
        - mysql-server

    - name: Make sure there is no such database
      shell: echo 'DROP DATABASE `declutter`' | mysql -u root
      ignore_errors: yes

    - name: Create database
      shell: echo 'CREATE DATABASE `declutter`' | mysql -u root

    - name: Create database structure
      shell: cat /vagrant/sql/structure.sql | mysql -u root declutter

    - name: Add node.js ppa repository
      apt_repository: repo='ppa:chris-lea/node.js'

    - name: Install needed packages
      apt: pkg={{ item }} state=latest
      with_items:
        - nodejs

    - name: Install node.js
      apt: pkg={{ item }} state=latest
      with_items:
        - nodejs

    - name: npm install
      npm: path=/vagrant

    - name: bower install
      shell: 'cd /vagrant/; node_modules/.bin/bower --allow-root install'

    - name: Copy upstart script
      shell: 'cp /vagrant/dev/declutter_upstart /etc/init/declutter.conf'

    - name: Start server
      shell: sudo start declutter
